package:
  name: ~#PROJECT#~
  version: 1.0.0

source:
  path: ..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
  build:
    #- {{ compiler('c') }}
  run:
    - python
    - docopt
    - python-json-logger
    - structlog
    - statsd
    - ujson
    - requests
    - lib_~#BASEPROJECT#~

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pycodestyle
    - black
  imports:
    - ~#PROJECT#~

about:
  home: ~#PROJECTLINK#~
  license: ~#LICENSE#~
  license_file: LICENSE
  summary: ~#SHORTDESCRIPTION#~
