language: python

dist: trusty

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

python:
  - 3.6

before_install:
  - sudo apt-get update || true
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;

addons:
  apt:
    packages:
    - python-autopep8

script:
  - make test
